### ISSUE TITLE
Reading Bruker data fails when data is stored in float format

### ISSUE THREAD

**Issue by jrm5100** [ManonMartin/PepsNMR#13]
Some Bruker data I have was loading incorrectly- it looked like the gain was set way too high- but other software and libraries loaded it fine.  I looked into the code of [NMRGlue](https://github.com/jjhelmus/nmrglue/blob/master/nmrglue/fileio/bruker.py) specifically, and found that there is a parameter indicating datatype:

```
# determine data type (assume int32 unless DTYPA is 2)
    if isfloat is None:
        isfloat = False     # default value
        if "acqus" in dic and "DTYPA" in dic["acqus"]:
            if dic["acqus"]["DTYPA"] == 2:
                isfloat = True
            else:
                isfloat = False
```

This data is from firmware version (DSPFVS) 21 and I'm not sure how early this parameter was added.  I tested it out and found that changing some of the `ReadBin` parameters in `ReadFid` fixed the issue.

Original:

```
readBin(fidFile, what = "int", n = TD, size=4L, endian = endianness)
```

Fixed:

```
readBin(fidFile, what = "double", n = TD, endian = endianness)
```

I would submit a pull request for this, but I'm not sure about the best way to organize this fix since the appropriate settings for readBin depend on a few different parameters.

**Comment by ManonMartin** [comment]
Hi John, 
Thanks for the issue reporting and the suggested solution! I will implement it asap in PepsNMR.
Best
