### ISSUE TITLE
Normalization with type.norm = "firstquartile"

### ISSUE THREAD

**Issue by breidan** [ManonMartin/PepsNMR#14]
Dear contributors,
I believe there is a bug in `Normalization`. If using `type.norm = "firstquartile"` the following error is thrown:

> Error in matrixStats::rowQuantiles(Spectrum_data, 0.25, na.rm = TRUE)[[1]] : subscript out of bounds

The cause of this is this line of code in `Normalization.R`:

> factor <- matrixStats::rowQuantiles(Spectrum_data, 0.25, na.rm = TRUE)[[1]]

the correct code should be:

>factor <- matrixStats::rowQuantiles(Spectrum_data, probs=0.25, na.rm = TRUE)

Works for me with this change.

**Comment by ManonMartin** [comment]
Hi,

Thank you for this issue, I just fixed it now.

Cheers
