### ISSUE TITLE
Alignment with non zero reference

### ISSUE THREAD

**Issue by pietrofranceschi** [ManonMartin/PepsNMR#16]
Dear Manon, 
first of all many thanks for your package and your work.
I'm using PepsNMR to process a set of lipidomic spectra and I have an issue in the Internal referencing phase.
In  our case we would like to use signal of chloroform as reference peak setting it to 7.26 ppm. 

![image](https://user-images.githubusercontent.com/5748138/127330562-55db8b11-094a-4798-96c9-8f8f7216ea0f.png)

As you can see the peak is clearly visible in all the spectra, but when I try to run the InternalReferencing function I get the following error  "ppm.value = 7.26 is not in the ppm interval [-7.27,4.7], and is set to its default ppm.value 0". 

The explicit code I'm running is the following

`test <- InternalReferencing(nmr_data$zopc[[1]],
                            nmr_data$fid_info[[1]], 
                            ppm.value = 7.26,
                            range = "window", 
                            method = "max", 
                            fromto.RC = list(c(7.5,7)))`

Am I doing something fundamentally wrong?

I've been trying to manually dig into the function and I've found something odd in the part where the ppm.scale is calculated

...

       TMSPpeaks <- apply(Re(Data), 1, which.max)
    }
    maxpeak <- max(TMSPpeaks)
    minpeak <- min(TMSPpeaks)
    if (shiftHandling %in% c("zerofilling", "NAfilling", "cut")) {
        fill <- NA
        if (shiftHandling == "zerofilling") {
            fill <- 0
        }
        start <- maxpeak - 1
        end <- minpeak - m
        ppmScale <- (start:end) * ppmInterval
        if (ppm.value < min(ppmScale) | ppm.value > max(ppmScale)) {
            warning("ppm.value = ", ppm.value, " is not in the ppm interval [", 
                round(min(ppmScale), 2), ",", round(max(ppmScale), 
                  2), "], and is set to its default ppm.value 0")
            ppm.value = 0
        }  

so, if I understand well, Data (which is already real), is a matrix full of constant small numbers with the exclusion of the spectral interval defined in the fromto.RC argument. This is to allow the identification of the maximum of each spectrum in the RC interval

TMSPpeaks should then contain the index of the chloroform maximum in all the individual samples, so maxpeak and minpeak are telling the range of variation of the maximum in term of column indices across the samples.

The new ppm scale is calculated from these values ... but why checking  if the reference value (ppm.value) is inside the range of ppmscale? (ppm.value < min(ppmScale) | ppm.value > max(ppmScale)). In my case everything works well if I remove the check.

![image](https://user-images.githubusercontent.com/5748138/127335635-f5c61597-63d8-4773-84a5-360e3f4ffd87.png)

Should the test be performed after the command

` ppmScale <- ppmScale + ppm.value`

?

Let me know and many thanks for your kind help.

all the best

Pietro

**Comment by ManonMartin** [comment]
Dear Pietro,

Thank you for spotting this bug and providing me with all your investigations. it has been solved accordingly.

Best,
Manon
